# Generated by Django 3.1.1 on 2021-06-06 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210606_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.user'),
        ),
    ]
