# Generated by Django 3.1.1 on 2021-06-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210606_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, to='network.Comment'),
        ),
    ]
